"""Install the background rotator as a systemd user service."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Callable

SERVICE_NAME = "hyprwall-rotator.service"
INSTALL_DIR = Path.home() / ".local" / "bin"
BINARY_NAME = "hyprwall"
UNIT_DIR = Path.home() / ".config" / "systemd" / "user"


def _current_binary() -> Path:
    return Path(sys.executable if getattr(sys, "frozen", False) else sys.argv[0]).resolve()


_WRAPPER_NAME = "hyprwall-rotator-start.sh"
_WRAPPER_PATH = INSTALL_DIR / _WRAPPER_NAME


def _write_wrapper_script(exec_start: str) -> None:
    """Write a shell wrapper that re-reads Hyprland's runtime env before launching.

    Hyprland exports HYPRLAND_INSTANCE_SIGNATURE and WAYLAND_DISPLAY into the
    systemd user environment via ``hyprland --import-environment``, but the
    timing is not guaranteed.  This wrapper polls until the signature is
    available (up to ~30 s) so the rotator never starts with a stale value.
    """
    INSTALL_DIR.mkdir(parents=True, exist_ok=True)
    script = (
        "#!/bin/sh\n"
        "# Auto-generated by HyprWall – do not edit manually.\n"
        "# Wait for Hyprland to export its runtime environment (up to 30 s).\n"
        "i=0\n"
        "while [ -z \"$HYPRLAND_INSTANCE_SIGNATURE\" ] && [ \"$i\" -lt 30 ]; do\n"
        "    sleep 1\n"
        "    i=$((i + 1))\n"
        "    # Re-import from the systemd user environment block.\n"
        "    eval \"$(systemctl --user show-environment 2>/dev/null \\\n"
        "        | grep -E '^(HYPRLAND_INSTANCE_SIGNATURE|WAYLAND_DISPLAY|DISPLAY|XDG_RUNTIME_DIR)=' \\\n"
        "        | sed 's/^/export /')\"\n"
        "done\n"
        f"exec {exec_start}\n"
    )
    _WRAPPER_PATH.write_text(script, encoding="utf-8")
    _WRAPPER_PATH.chmod(0o755)


def install_and_enable(log: Callable[[str], None]) -> None:
    if not shutil.which("systemctl"):
        log("systemd not available - skipping autostart setup.")
        return
    source = _current_binary()
    if getattr(sys, "frozen", False):
        target = INSTALL_DIR / BINARY_NAME
        INSTALL_DIR.mkdir(parents=True, exist_ok=True)
        if not target.exists() or target.stat().st_mtime < source.stat().st_mtime:
            shutil.copy2(source, target)
            target.chmod(0o755)
        exec_cmd = f"{target} --rotator"
    else:
        target = source
        exec_cmd = f"{sys.executable} {source} --rotator"

    _write_wrapper_script(exec_cmd)

    env_lines = []
    for key in ("DISPLAY", "WAYLAND_DISPLAY", "XDG_RUNTIME_DIR", "HYPRLAND_INSTANCE_SIGNATURE"):
        value = os.environ.get(key)
        if value:
            env_lines.append(f"Environment={key}={value}")

    UNIT_DIR.mkdir(parents=True, exist_ok=True)
    unit_text = (
        "[Unit]\n"
        "Description=HyprWall wallpaper rotator\n"
        "Wants=graphical-session.target\n"
        "After=graphical-session.target\n\n"
        "[Service]\n"
    )
    if env_lines:
        unit_text += "\n".join(env_lines) + "\n"
    unit_text += (
        # Do NOT hard-code session env here – values change on every login.
        # The wrapper script polls systemd's live environment instead.
        f"ExecStart={_WRAPPER_PATH}\n"
        "Type=simple\n"
        "MemoryHigh=300M\n"
        "MemoryMax=512M\n"
        "TasksMax=25\n"
        "Restart=on-failure\n"
        "RestartSec=5\n\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )
    (UNIT_DIR / SERVICE_NAME).write_text(unit_text, encoding="utf-8")
    subprocess.run(["systemctl", "--user", "daemon-reload"], check=False, capture_output=True)
    subprocess.run(
        ["systemctl", "--user", "import-environment",
         "DISPLAY", "WAYLAND_DISPLAY", "XDG_RUNTIME_DIR", "HYPRLAND_INSTANCE_SIGNATURE"],
        check=False,
        capture_output=True,
    )
    subprocess.run(["systemctl", "--user", "enable", "--now", SERVICE_NAME], check=False, capture_output=True)
    log(f"Background rotator installed and enabled ({SERVICE_NAME}).")


def disable(log: Callable[[str], None]) -> None:
    """Stop the rotator service without affecting the GUI."""
    if shutil.which("systemctl"):
        subprocess.run(["systemctl", "--user", "disable", "--now", SERVICE_NAME], check=False, capture_output=True)
    if _WRAPPER_PATH.exists():
        _WRAPPER_PATH.unlink()
    log("Background rotator disabled.")


def cleanup_legacy_service(log: Callable[[str], None]) -> None:
    old_names = ("desktop-live-linux-rotator.service", "wallpaper-rotator.service")
    for old_name in old_names:
        old_unit = UNIT_DIR / old_name
        if old_unit.exists() and shutil.which("systemctl"):
            subprocess.run(["systemctl", "--user", "disable", "--now", old_name], check=False, capture_output=True)
        if old_unit.exists():
            old_unit.unlink()
    legacy_units = [
        UNIT_DIR / "desktop-live-linux-rotator.service",
        UNIT_DIR / "wallpaper-rotator.service",
        UNIT_DIR / "desktop-live-linux.service",
        UNIT_DIR / "hyprwall-rotator.service",
    ]
    for unit_path in legacy_units:
        if unit_path.exists() and unit_path.name != SERVICE_NAME:
            if shutil.which("systemctl"):
                subprocess.run(["systemctl", "--user", "disable", "--now", unit_path.name], check=False, capture_output=True)
            unit_path.unlink()
    old_binary = INSTALL_DIR / "desktop-live-linux"
    if old_binary.exists():
        old_binary.unlink()
    if shutil.which("systemctl"):
        subprocess.run(["systemctl", "--user", "daemon-reload"], check=False, capture_output=True)
    log("Legacy autostart config cleaned up.")